### ISSUE TITLE
浏览器进行缩放时会出现壁纸无法覆盖整个屏幕

### ISSUE THREAD

**Issue by Sharkkkk** [ihardcoder/bing-demo#1]
其他方面都很完美，希望作者能修复这个小问题

**Comment by zhoujunpeng** [comment]
@Sharkkkk 感谢关注，这个demo只做展示用，并不是非常严谨，对应的文章可以参考http://www.cnblogs.com/ihardcoder/p/4894194.html。

**Comment by Sharkkkk** [comment]
嗯嗯，这篇文章我看过了。我也是通过这篇文章找到的代码，不过还是希望你能修复一下这个代码。因为我想用在校园导航上。。。。可惜自己试了很多次都修复不成功
